package com.yumi.cash.app.server.dao;

public class ProductBasicInfoWithBLOBs extends ProductBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yumi-cash..PRODUCT_BASIC_INFO.INTEREST_TYPE
     *
     * @mbggenerated
     */
    private String interestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yumi-cash..PRODUCT_BASIC_INFO.APPLY_CRITERIA
     *
     * @mbggenerated
     */
    private String applyCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yumi-cash..PRODUCT_BASIC_INFO.APPLY_MATERIAL
     *
     * @mbggenerated
     */
    private String applyMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yumi-cash..PRODUCT_BASIC_INFO.ADVANCE_REPAY_DESC
     *
     * @mbggenerated
     */
    private String advanceRepayDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yumi-cash..PRODUCT_BASIC_INFO.GUIDE
     *
     * @mbggenerated
     */
    private String guide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yumi-cash..PRODUCT_BASIC_INFO.INTEREST_TYPE
     *
     * @return the value of yumi-cash..PRODUCT_BASIC_INFO.INTEREST_TYPE
     *
     * @mbggenerated
     */
    public String getInterestType() {
        return interestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yumi-cash..PRODUCT_BASIC_INFO.INTEREST_TYPE
     *
     * @param interestType the value for yumi-cash..PRODUCT_BASIC_INFO.INTEREST_TYPE
     *
     * @mbggenerated
     */
    public void setInterestType(String interestType) {
        this.interestType = interestType == null ? null : interestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yumi-cash..PRODUCT_BASIC_INFO.APPLY_CRITERIA
     *
     * @return the value of yumi-cash..PRODUCT_BASIC_INFO.APPLY_CRITERIA
     *
     * @mbggenerated
     */
    public String getApplyCriteria() {
        return applyCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yumi-cash..PRODUCT_BASIC_INFO.APPLY_CRITERIA
     *
     * @param applyCriteria the value for yumi-cash..PRODUCT_BASIC_INFO.APPLY_CRITERIA
     *
     * @mbggenerated
     */
    public void setApplyCriteria(String applyCriteria) {
        this.applyCriteria = applyCriteria == null ? null : applyCriteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yumi-cash..PRODUCT_BASIC_INFO.APPLY_MATERIAL
     *
     * @return the value of yumi-cash..PRODUCT_BASIC_INFO.APPLY_MATERIAL
     *
     * @mbggenerated
     */
    public String getApplyMaterial() {
        return applyMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yumi-cash..PRODUCT_BASIC_INFO.APPLY_MATERIAL
     *
     * @param applyMaterial the value for yumi-cash..PRODUCT_BASIC_INFO.APPLY_MATERIAL
     *
     * @mbggenerated
     */
    public void setApplyMaterial(String applyMaterial) {
        this.applyMaterial = applyMaterial == null ? null : applyMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yumi-cash..PRODUCT_BASIC_INFO.ADVANCE_REPAY_DESC
     *
     * @return the value of yumi-cash..PRODUCT_BASIC_INFO.ADVANCE_REPAY_DESC
     *
     * @mbggenerated
     */
    public String getAdvanceRepayDesc() {
        return advanceRepayDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yumi-cash..PRODUCT_BASIC_INFO.ADVANCE_REPAY_DESC
     *
     * @param advanceRepayDesc the value for yumi-cash..PRODUCT_BASIC_INFO.ADVANCE_REPAY_DESC
     *
     * @mbggenerated
     */
    public void setAdvanceRepayDesc(String advanceRepayDesc) {
        this.advanceRepayDesc = advanceRepayDesc == null ? null : advanceRepayDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yumi-cash..PRODUCT_BASIC_INFO.GUIDE
     *
     * @return the value of yumi-cash..PRODUCT_BASIC_INFO.GUIDE
     *
     * @mbggenerated
     */
    public String getGuide() {
        return guide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yumi-cash..PRODUCT_BASIC_INFO.GUIDE
     *
     * @param guide the value for yumi-cash..PRODUCT_BASIC_INFO.GUIDE
     *
     * @mbggenerated
     */
    public void setGuide(String guide) {
        this.guide = guide == null ? null : guide.trim();
    }
}