package com.yumi.cash.app.server.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProductBasicInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public ProductBasicInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("PRODUCT_ID like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("PRODUCT_ID not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProdNameIsNull() {
            addCriterion("PROD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProdNameIsNotNull() {
            addCriterion("PROD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProdNameEqualTo(String value) {
            addCriterion("PROD_NAME =", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotEqualTo(String value) {
            addCriterion("PROD_NAME <>", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameGreaterThan(String value) {
            addCriterion("PROD_NAME >", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_NAME >=", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLessThan(String value) {
            addCriterion("PROD_NAME <", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLessThanOrEqualTo(String value) {
            addCriterion("PROD_NAME <=", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLike(String value) {
            addCriterion("PROD_NAME like", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotLike(String value) {
            addCriterion("PROD_NAME not like", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameIn(List<String> values) {
            addCriterion("PROD_NAME in", values, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotIn(List<String> values) {
            addCriterion("PROD_NAME not in", values, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameBetween(String value1, String value2) {
            addCriterion("PROD_NAME between", value1, value2, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotBetween(String value1, String value2) {
            addCriterion("PROD_NAME not between", value1, value2, "prodName");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNull() {
            addCriterion("LOGO_URL is null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNotNull() {
            addCriterion("LOGO_URL is not null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlEqualTo(String value) {
            addCriterion("LOGO_URL =", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotEqualTo(String value) {
            addCriterion("LOGO_URL <>", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThan(String value) {
            addCriterion("LOGO_URL >", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("LOGO_URL >=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThan(String value) {
            addCriterion("LOGO_URL <", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("LOGO_URL <=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLike(String value) {
            addCriterion("LOGO_URL like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotLike(String value) {
            addCriterion("LOGO_URL not like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIn(List<String> values) {
            addCriterion("LOGO_URL in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotIn(List<String> values) {
            addCriterion("LOGO_URL not in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlBetween(String value1, String value2) {
            addCriterion("LOGO_URL between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotBetween(String value1, String value2) {
            addCriterion("LOGO_URL not between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andProdDescIsNull() {
            addCriterion("PROD_DESC is null");
            return (Criteria) this;
        }

        public Criteria andProdDescIsNotNull() {
            addCriterion("PROD_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andProdDescEqualTo(String value) {
            addCriterion("PROD_DESC =", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotEqualTo(String value) {
            addCriterion("PROD_DESC <>", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescGreaterThan(String value) {
            addCriterion("PROD_DESC >", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_DESC >=", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescLessThan(String value) {
            addCriterion("PROD_DESC <", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescLessThanOrEqualTo(String value) {
            addCriterion("PROD_DESC <=", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescLike(String value) {
            addCriterion("PROD_DESC like", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotLike(String value) {
            addCriterion("PROD_DESC not like", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescIn(List<String> values) {
            addCriterion("PROD_DESC in", values, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotIn(List<String> values) {
            addCriterion("PROD_DESC not in", values, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescBetween(String value1, String value2) {
            addCriterion("PROD_DESC between", value1, value2, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotBetween(String value1, String value2) {
            addCriterion("PROD_DESC not between", value1, value2, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("STAT is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("STAT is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(String value) {
            addCriterion("STAT =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(String value) {
            addCriterion("STAT <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(String value) {
            addCriterion("STAT >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(String value) {
            addCriterion("STAT >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(String value) {
            addCriterion("STAT <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(String value) {
            addCriterion("STAT <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLike(String value) {
            addCriterion("STAT like", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotLike(String value) {
            addCriterion("STAT not like", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<String> values) {
            addCriterion("STAT in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<String> values) {
            addCriterion("STAT not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(String value1, String value2) {
            addCriterion("STAT between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(String value1, String value2) {
            addCriterion("STAT not between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andProductUrlIsNull() {
            addCriterion("PRODUCT_URL is null");
            return (Criteria) this;
        }

        public Criteria andProductUrlIsNotNull() {
            addCriterion("PRODUCT_URL is not null");
            return (Criteria) this;
        }

        public Criteria andProductUrlEqualTo(String value) {
            addCriterion("PRODUCT_URL =", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotEqualTo(String value) {
            addCriterion("PRODUCT_URL <>", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlGreaterThan(String value) {
            addCriterion("PRODUCT_URL >", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_URL >=", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlLessThan(String value) {
            addCriterion("PRODUCT_URL <", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_URL <=", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlLike(String value) {
            addCriterion("PRODUCT_URL like", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotLike(String value) {
            addCriterion("PRODUCT_URL not like", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlIn(List<String> values) {
            addCriterion("PRODUCT_URL in", values, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotIn(List<String> values) {
            addCriterion("PRODUCT_URL not in", values, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlBetween(String value1, String value2) {
            addCriterion("PRODUCT_URL between", value1, value2, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_URL not between", value1, value2, "productUrl");
            return (Criteria) this;
        }

        public Criteria andSuitableCityIsNull() {
            addCriterion("SUITABLE_CITY is null");
            return (Criteria) this;
        }

        public Criteria andSuitableCityIsNotNull() {
            addCriterion("SUITABLE_CITY is not null");
            return (Criteria) this;
        }

        public Criteria andSuitableCityEqualTo(String value) {
            addCriterion("SUITABLE_CITY =", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityNotEqualTo(String value) {
            addCriterion("SUITABLE_CITY <>", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityGreaterThan(String value) {
            addCriterion("SUITABLE_CITY >", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityGreaterThanOrEqualTo(String value) {
            addCriterion("SUITABLE_CITY >=", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityLessThan(String value) {
            addCriterion("SUITABLE_CITY <", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityLessThanOrEqualTo(String value) {
            addCriterion("SUITABLE_CITY <=", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityLike(String value) {
            addCriterion("SUITABLE_CITY like", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityNotLike(String value) {
            addCriterion("SUITABLE_CITY not like", value, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityIn(List<String> values) {
            addCriterion("SUITABLE_CITY in", values, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityNotIn(List<String> values) {
            addCriterion("SUITABLE_CITY not in", values, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityBetween(String value1, String value2) {
            addCriterion("SUITABLE_CITY between", value1, value2, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andSuitableCityNotBetween(String value1, String value2) {
            addCriterion("SUITABLE_CITY not between", value1, value2, "suitableCity");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitIsNull() {
            addCriterion("MAX_LOAN_LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitIsNotNull() {
            addCriterion("MAX_LOAN_LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_LIMIT =", value, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitNotEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_LIMIT <>", value, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitGreaterThan(BigDecimal value) {
            addCriterion("MAX_LOAN_LIMIT >", value, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_LIMIT >=", value, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitLessThan(BigDecimal value) {
            addCriterion("MAX_LOAN_LIMIT <", value, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_LIMIT <=", value, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitIn(List<BigDecimal> values) {
            addCriterion("MAX_LOAN_LIMIT in", values, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitNotIn(List<BigDecimal> values) {
            addCriterion("MAX_LOAN_LIMIT not in", values, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAX_LOAN_LIMIT between", value1, value2, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAX_LOAN_LIMIT not between", value1, value2, "maxLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitIsNull() {
            addCriterion("MIN_LOAN_LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitIsNotNull() {
            addCriterion("MIN_LOAN_LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_LIMIT =", value, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitNotEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_LIMIT <>", value, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitGreaterThan(BigDecimal value) {
            addCriterion("MIN_LOAN_LIMIT >", value, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_LIMIT >=", value, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitLessThan(BigDecimal value) {
            addCriterion("MIN_LOAN_LIMIT <", value, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_LIMIT <=", value, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitIn(List<BigDecimal> values) {
            addCriterion("MIN_LOAN_LIMIT in", values, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitNotIn(List<BigDecimal> values) {
            addCriterion("MIN_LOAN_LIMIT not in", values, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MIN_LOAN_LIMIT between", value1, value2, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMinLoanLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MIN_LOAN_LIMIT not between", value1, value2, "minLoanLimit");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodIsNull() {
            addCriterion("MAX_LOAN_PERIOD is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodIsNotNull() {
            addCriterion("MAX_LOAN_PERIOD is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_PERIOD =", value, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodNotEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_PERIOD <>", value, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodGreaterThan(BigDecimal value) {
            addCriterion("MAX_LOAN_PERIOD >", value, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_PERIOD >=", value, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodLessThan(BigDecimal value) {
            addCriterion("MAX_LOAN_PERIOD <", value, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MAX_LOAN_PERIOD <=", value, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodIn(List<BigDecimal> values) {
            addCriterion("MAX_LOAN_PERIOD in", values, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodNotIn(List<BigDecimal> values) {
            addCriterion("MAX_LOAN_PERIOD not in", values, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAX_LOAN_PERIOD between", value1, value2, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxLoanPeriodNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAX_LOAN_PERIOD not between", value1, value2, "maxLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodIsNull() {
            addCriterion("MIN_LOAN_PERIOD is null");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodIsNotNull() {
            addCriterion("MIN_LOAN_PERIOD is not null");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_PERIOD =", value, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodNotEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_PERIOD <>", value, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodGreaterThan(BigDecimal value) {
            addCriterion("MIN_LOAN_PERIOD >", value, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_PERIOD >=", value, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodLessThan(BigDecimal value) {
            addCriterion("MIN_LOAN_PERIOD <", value, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MIN_LOAN_PERIOD <=", value, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodIn(List<BigDecimal> values) {
            addCriterion("MIN_LOAN_PERIOD in", values, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodNotIn(List<BigDecimal> values) {
            addCriterion("MIN_LOAN_PERIOD not in", values, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MIN_LOAN_PERIOD between", value1, value2, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andMinLoanPeriodNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MIN_LOAN_PERIOD not between", value1, value2, "minLoanPeriod");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIsNull() {
            addCriterion("PERIOD_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIsNotNull() {
            addCriterion("PERIOD_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitEqualTo(String value) {
            addCriterion("PERIOD_UNIT =", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotEqualTo(String value) {
            addCriterion("PERIOD_UNIT <>", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitGreaterThan(String value) {
            addCriterion("PERIOD_UNIT >", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitGreaterThanOrEqualTo(String value) {
            addCriterion("PERIOD_UNIT >=", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLessThan(String value) {
            addCriterion("PERIOD_UNIT <", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLessThanOrEqualTo(String value) {
            addCriterion("PERIOD_UNIT <=", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLike(String value) {
            addCriterion("PERIOD_UNIT like", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotLike(String value) {
            addCriterion("PERIOD_UNIT not like", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIn(List<String> values) {
            addCriterion("PERIOD_UNIT in", values, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotIn(List<String> values) {
            addCriterion("PERIOD_UNIT not in", values, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitBetween(String value1, String value2) {
            addCriterion("PERIOD_UNIT between", value1, value2, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotBetween(String value1, String value2) {
            addCriterion("PERIOD_UNIT not between", value1, value2, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andYieldIsNull() {
            addCriterion("YIELD is null");
            return (Criteria) this;
        }

        public Criteria andYieldIsNotNull() {
            addCriterion("YIELD is not null");
            return (Criteria) this;
        }

        public Criteria andYieldEqualTo(BigDecimal value) {
            addCriterion("YIELD =", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotEqualTo(BigDecimal value) {
            addCriterion("YIELD <>", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldGreaterThan(BigDecimal value) {
            addCriterion("YIELD >", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YIELD >=", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldLessThan(BigDecimal value) {
            addCriterion("YIELD <", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YIELD <=", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldIn(List<BigDecimal> values) {
            addCriterion("YIELD in", values, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotIn(List<BigDecimal> values) {
            addCriterion("YIELD not in", values, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YIELD between", value1, value2, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YIELD not between", value1, value2, "yield");
            return (Criteria) this;
        }

        public Criteria andFeeRateIsNull() {
            addCriterion("FEE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andFeeRateIsNotNull() {
            addCriterion("FEE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andFeeRateEqualTo(BigDecimal value) {
            addCriterion("FEE_RATE =", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("FEE_RATE <>", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateGreaterThan(BigDecimal value) {
            addCriterion("FEE_RATE >", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_RATE >=", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLessThan(BigDecimal value) {
            addCriterion("FEE_RATE <", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEE_RATE <=", value, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateIn(List<BigDecimal> values) {
            addCriterion("FEE_RATE in", values, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("FEE_RATE not in", values, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_RATE between", value1, value2, "feeRate");
            return (Criteria) this;
        }

        public Criteria andFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEE_RATE not between", value1, value2, "feeRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateIsNull() {
            addCriterion("MONTH_RATE is null");
            return (Criteria) this;
        }

        public Criteria andMonthRateIsNotNull() {
            addCriterion("MONTH_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andMonthRateEqualTo(BigDecimal value) {
            addCriterion("MONTH_RATE =", value, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateNotEqualTo(BigDecimal value) {
            addCriterion("MONTH_RATE <>", value, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateGreaterThan(BigDecimal value) {
            addCriterion("MONTH_RATE >", value, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MONTH_RATE >=", value, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateLessThan(BigDecimal value) {
            addCriterion("MONTH_RATE <", value, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MONTH_RATE <=", value, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateIn(List<BigDecimal> values) {
            addCriterion("MONTH_RATE in", values, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateNotIn(List<BigDecimal> values) {
            addCriterion("MONTH_RATE not in", values, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MONTH_RATE between", value1, value2, "monthRate");
            return (Criteria) this;
        }

        public Criteria andMonthRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MONTH_RATE not between", value1, value2, "monthRate");
            return (Criteria) this;
        }

        public Criteria andDayRateIsNull() {
            addCriterion("DAY_RATE is null");
            return (Criteria) this;
        }

        public Criteria andDayRateIsNotNull() {
            addCriterion("DAY_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andDayRateEqualTo(BigDecimal value) {
            addCriterion("DAY_RATE =", value, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateNotEqualTo(BigDecimal value) {
            addCriterion("DAY_RATE <>", value, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateGreaterThan(BigDecimal value) {
            addCriterion("DAY_RATE >", value, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DAY_RATE >=", value, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateLessThan(BigDecimal value) {
            addCriterion("DAY_RATE <", value, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DAY_RATE <=", value, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateIn(List<BigDecimal> values) {
            addCriterion("DAY_RATE in", values, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateNotIn(List<BigDecimal> values) {
            addCriterion("DAY_RATE not in", values, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DAY_RATE between", value1, value2, "dayRate");
            return (Criteria) this;
        }

        public Criteria andDayRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DAY_RATE not between", value1, value2, "dayRate");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeIsNull() {
            addCriterion("PUT_MONEY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeIsNotNull() {
            addCriterion("PUT_MONEY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeEqualTo(BigDecimal value) {
            addCriterion("PUT_MONEY_TIME =", value, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeNotEqualTo(BigDecimal value) {
            addCriterion("PUT_MONEY_TIME <>", value, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeGreaterThan(BigDecimal value) {
            addCriterion("PUT_MONEY_TIME >", value, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PUT_MONEY_TIME >=", value, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeLessThan(BigDecimal value) {
            addCriterion("PUT_MONEY_TIME <", value, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PUT_MONEY_TIME <=", value, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeIn(List<BigDecimal> values) {
            addCriterion("PUT_MONEY_TIME in", values, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeNotIn(List<BigDecimal> values) {
            addCriterion("PUT_MONEY_TIME not in", values, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PUT_MONEY_TIME between", value1, value2, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PUT_MONEY_TIME not between", value1, value2, "putMoneyTime");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitIsNull() {
            addCriterion("PUT_MONEY_TIME_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitIsNotNull() {
            addCriterion("PUT_MONEY_TIME_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitEqualTo(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT =", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitNotEqualTo(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT <>", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitGreaterThan(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT >", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitGreaterThanOrEqualTo(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT >=", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitLessThan(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT <", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitLessThanOrEqualTo(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT <=", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitLike(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT like", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitNotLike(String value) {
            addCriterion("PUT_MONEY_TIME_UNIT not like", value, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitIn(List<String> values) {
            addCriterion("PUT_MONEY_TIME_UNIT in", values, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitNotIn(List<String> values) {
            addCriterion("PUT_MONEY_TIME_UNIT not in", values, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitBetween(String value1, String value2) {
            addCriterion("PUT_MONEY_TIME_UNIT between", value1, value2, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andPutMoneyTimeUnitNotBetween(String value1, String value2) {
            addCriterion("PUT_MONEY_TIME_UNIT not between", value1, value2, "putMoneyTimeUnit");
            return (Criteria) this;
        }

        public Criteria andRepayMannerIsNull() {
            addCriterion("REPAY_MANNER is null");
            return (Criteria) this;
        }

        public Criteria andRepayMannerIsNotNull() {
            addCriterion("REPAY_MANNER is not null");
            return (Criteria) this;
        }

        public Criteria andRepayMannerEqualTo(String value) {
            addCriterion("REPAY_MANNER =", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerNotEqualTo(String value) {
            addCriterion("REPAY_MANNER <>", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerGreaterThan(String value) {
            addCriterion("REPAY_MANNER >", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerGreaterThanOrEqualTo(String value) {
            addCriterion("REPAY_MANNER >=", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerLessThan(String value) {
            addCriterion("REPAY_MANNER <", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerLessThanOrEqualTo(String value) {
            addCriterion("REPAY_MANNER <=", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerLike(String value) {
            addCriterion("REPAY_MANNER like", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerNotLike(String value) {
            addCriterion("REPAY_MANNER not like", value, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerIn(List<String> values) {
            addCriterion("REPAY_MANNER in", values, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerNotIn(List<String> values) {
            addCriterion("REPAY_MANNER not in", values, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerBetween(String value1, String value2) {
            addCriterion("REPAY_MANNER between", value1, value2, "repayManner");
            return (Criteria) this;
        }

        public Criteria andRepayMannerNotBetween(String value1, String value2) {
            addCriterion("REPAY_MANNER not between", value1, value2, "repayManner");
            return (Criteria) this;
        }

        public Criteria andProdNameEnIsNull() {
            addCriterion("PROD_NAME_EN is null");
            return (Criteria) this;
        }

        public Criteria andProdNameEnIsNotNull() {
            addCriterion("PROD_NAME_EN is not null");
            return (Criteria) this;
        }

        public Criteria andProdNameEnEqualTo(String value) {
            addCriterion("PROD_NAME_EN =", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnNotEqualTo(String value) {
            addCriterion("PROD_NAME_EN <>", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnGreaterThan(String value) {
            addCriterion("PROD_NAME_EN >", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_NAME_EN >=", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnLessThan(String value) {
            addCriterion("PROD_NAME_EN <", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnLessThanOrEqualTo(String value) {
            addCriterion("PROD_NAME_EN <=", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnLike(String value) {
            addCriterion("PROD_NAME_EN like", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnNotLike(String value) {
            addCriterion("PROD_NAME_EN not like", value, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnIn(List<String> values) {
            addCriterion("PROD_NAME_EN in", values, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnNotIn(List<String> values) {
            addCriterion("PROD_NAME_EN not in", values, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnBetween(String value1, String value2) {
            addCriterion("PROD_NAME_EN between", value1, value2, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andProdNameEnNotBetween(String value1, String value2) {
            addCriterion("PROD_NAME_EN not between", value1, value2, "prodNameEn");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Short value) {
            addCriterion("WEIGHT =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Short value) {
            addCriterion("WEIGHT <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Short value) {
            addCriterion("WEIGHT >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Short value) {
            addCriterion("WEIGHT >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Short value) {
            addCriterion("WEIGHT <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Short value) {
            addCriterion("WEIGHT <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Short> values) {
            addCriterion("WEIGHT in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Short> values) {
            addCriterion("WEIGHT not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Short value1, Short value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Short value1, Short value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andProdCatgIsNull() {
            addCriterion("PROD_CATG is null");
            return (Criteria) this;
        }

        public Criteria andProdCatgIsNotNull() {
            addCriterion("PROD_CATG is not null");
            return (Criteria) this;
        }

        public Criteria andProdCatgEqualTo(String value) {
            addCriterion("PROD_CATG =", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgNotEqualTo(String value) {
            addCriterion("PROD_CATG <>", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgGreaterThan(String value) {
            addCriterion("PROD_CATG >", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_CATG >=", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgLessThan(String value) {
            addCriterion("PROD_CATG <", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgLessThanOrEqualTo(String value) {
            addCriterion("PROD_CATG <=", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgLike(String value) {
            addCriterion("PROD_CATG like", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgNotLike(String value) {
            addCriterion("PROD_CATG not like", value, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgIn(List<String> values) {
            addCriterion("PROD_CATG in", values, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgNotIn(List<String> values) {
            addCriterion("PROD_CATG not in", values, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgBetween(String value1, String value2) {
            addCriterion("PROD_CATG between", value1, value2, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andProdCatgNotBetween(String value1, String value2) {
            addCriterion("PROD_CATG not between", value1, value2, "prodCatg");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeIsNull() {
            addCriterion("APPLY_ACTION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeIsNotNull() {
            addCriterion("APPLY_ACTION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeEqualTo(Short value) {
            addCriterion("APPLY_ACTION_TYPE =", value, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeNotEqualTo(Short value) {
            addCriterion("APPLY_ACTION_TYPE <>", value, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeGreaterThan(Short value) {
            addCriterion("APPLY_ACTION_TYPE >", value, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("APPLY_ACTION_TYPE >=", value, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeLessThan(Short value) {
            addCriterion("APPLY_ACTION_TYPE <", value, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeLessThanOrEqualTo(Short value) {
            addCriterion("APPLY_ACTION_TYPE <=", value, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeIn(List<Short> values) {
            addCriterion("APPLY_ACTION_TYPE in", values, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeNotIn(List<Short> values) {
            addCriterion("APPLY_ACTION_TYPE not in", values, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeBetween(Short value1, Short value2) {
            addCriterion("APPLY_ACTION_TYPE between", value1, value2, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApplyActionTypeNotBetween(Short value1, Short value2) {
            addCriterion("APPLY_ACTION_TYPE not between", value1, value2, "applyActionType");
            return (Criteria) this;
        }

        public Criteria andApppyMethodIsNull() {
            addCriterion("APPPY_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andApppyMethodIsNotNull() {
            addCriterion("APPPY_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andApppyMethodEqualTo(String value) {
            addCriterion("APPPY_METHOD =", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodNotEqualTo(String value) {
            addCriterion("APPPY_METHOD <>", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodGreaterThan(String value) {
            addCriterion("APPPY_METHOD >", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodGreaterThanOrEqualTo(String value) {
            addCriterion("APPPY_METHOD >=", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodLessThan(String value) {
            addCriterion("APPPY_METHOD <", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodLessThanOrEqualTo(String value) {
            addCriterion("APPPY_METHOD <=", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodLike(String value) {
            addCriterion("APPPY_METHOD like", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodNotLike(String value) {
            addCriterion("APPPY_METHOD not like", value, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodIn(List<String> values) {
            addCriterion("APPPY_METHOD in", values, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodNotIn(List<String> values) {
            addCriterion("APPPY_METHOD not in", values, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodBetween(String value1, String value2) {
            addCriterion("APPPY_METHOD between", value1, value2, "apppyMethod");
            return (Criteria) this;
        }

        public Criteria andApppyMethodNotBetween(String value1, String value2) {
            addCriterion("APPPY_METHOD not between", value1, value2, "apppyMethod");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}