package com.yumi.cash.app.server.dao;

import java.math.BigDecimal;

public class ProductBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PROD_NAME
     *
     * @mbggenerated
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.LOGO_URL
     *
     * @mbggenerated
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PROD_DESC
     *
     * @mbggenerated
     */
    private String prodDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.STAT
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PRODUCT_URL
     *
     * @mbggenerated
     */
    private String productUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.SUITABLE_CITY
     *
     * @mbggenerated
     */
    private String suitableCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.MAX_LOAN_LIMIT
     *
     * @mbggenerated
     */
    private BigDecimal maxLoanLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.MIN_LOAN_LIMIT
     *
     * @mbggenerated
     */
    private BigDecimal minLoanLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.MAX_LOAN_PERIOD
     *
     * @mbggenerated
     */
    private BigDecimal maxLoanPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.MIN_LOAN_PERIOD
     *
     * @mbggenerated
     */
    private BigDecimal minLoanPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PERIOD_UNIT
     *
     * @mbggenerated
     */
    private String periodUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.YIELD
     *
     * @mbggenerated
     */
    private BigDecimal yield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.FEE_RATE
     *
     * @mbggenerated
     */
    private BigDecimal feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.MONTH_RATE
     *
     * @mbggenerated
     */
    private BigDecimal monthRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.DAY_RATE
     *
     * @mbggenerated
     */
    private BigDecimal dayRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PUT_MONEY_TIME
     *
     * @mbggenerated
     */
    private BigDecimal putMoneyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PUT_MONEY_TIME_UNIT
     *
     * @mbggenerated
     */
    private String putMoneyTimeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.REPAY_MANNER
     *
     * @mbggenerated
     */
    private String repayManner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PROD_NAME_EN
     *
     * @mbggenerated
     */
    private String prodNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.WEIGHT
     *
     * @mbggenerated
     */
    private Short weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.PROD_CATG
     *
     * @mbggenerated
     */
    private String prodCatg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.APPLY_ACTION_TYPE
     *
     * @mbggenerated
     */
    private Short applyActionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_BASIC_INFO.APPPY_METHOD
     *
     * @mbggenerated
     */
    private String apppyMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PRODUCT_ID
     *
     * @return the value of PRODUCT_BASIC_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PRODUCT_ID
     *
     * @param productId the value for PRODUCT_BASIC_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PROD_NAME
     *
     * @return the value of PRODUCT_BASIC_INFO.PROD_NAME
     *
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PROD_NAME
     *
     * @param prodName the value for PRODUCT_BASIC_INFO.PROD_NAME
     *
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.LOGO_URL
     *
     * @return the value of PRODUCT_BASIC_INFO.LOGO_URL
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.LOGO_URL
     *
     * @param logoUrl the value for PRODUCT_BASIC_INFO.LOGO_URL
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PROD_DESC
     *
     * @return the value of PRODUCT_BASIC_INFO.PROD_DESC
     *
     * @mbggenerated
     */
    public String getProdDesc() {
        return prodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PROD_DESC
     *
     * @param prodDesc the value for PRODUCT_BASIC_INFO.PROD_DESC
     *
     * @mbggenerated
     */
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc == null ? null : prodDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.STAT
     *
     * @return the value of PRODUCT_BASIC_INFO.STAT
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.STAT
     *
     * @param stat the value for PRODUCT_BASIC_INFO.STAT
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PRODUCT_URL
     *
     * @return the value of PRODUCT_BASIC_INFO.PRODUCT_URL
     *
     * @mbggenerated
     */
    public String getProductUrl() {
        return productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PRODUCT_URL
     *
     * @param productUrl the value for PRODUCT_BASIC_INFO.PRODUCT_URL
     *
     * @mbggenerated
     */
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl == null ? null : productUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.SUITABLE_CITY
     *
     * @return the value of PRODUCT_BASIC_INFO.SUITABLE_CITY
     *
     * @mbggenerated
     */
    public String getSuitableCity() {
        return suitableCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.SUITABLE_CITY
     *
     * @param suitableCity the value for PRODUCT_BASIC_INFO.SUITABLE_CITY
     *
     * @mbggenerated
     */
    public void setSuitableCity(String suitableCity) {
        this.suitableCity = suitableCity == null ? null : suitableCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.MAX_LOAN_LIMIT
     *
     * @return the value of PRODUCT_BASIC_INFO.MAX_LOAN_LIMIT
     *
     * @mbggenerated
     */
    public BigDecimal getMaxLoanLimit() {
        return maxLoanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.MAX_LOAN_LIMIT
     *
     * @param maxLoanLimit the value for PRODUCT_BASIC_INFO.MAX_LOAN_LIMIT
     *
     * @mbggenerated
     */
    public void setMaxLoanLimit(BigDecimal maxLoanLimit) {
        this.maxLoanLimit = maxLoanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.MIN_LOAN_LIMIT
     *
     * @return the value of PRODUCT_BASIC_INFO.MIN_LOAN_LIMIT
     *
     * @mbggenerated
     */
    public BigDecimal getMinLoanLimit() {
        return minLoanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.MIN_LOAN_LIMIT
     *
     * @param minLoanLimit the value for PRODUCT_BASIC_INFO.MIN_LOAN_LIMIT
     *
     * @mbggenerated
     */
    public void setMinLoanLimit(BigDecimal minLoanLimit) {
        this.minLoanLimit = minLoanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.MAX_LOAN_PERIOD
     *
     * @return the value of PRODUCT_BASIC_INFO.MAX_LOAN_PERIOD
     *
     * @mbggenerated
     */
    public BigDecimal getMaxLoanPeriod() {
        return maxLoanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.MAX_LOAN_PERIOD
     *
     * @param maxLoanPeriod the value for PRODUCT_BASIC_INFO.MAX_LOAN_PERIOD
     *
     * @mbggenerated
     */
    public void setMaxLoanPeriod(BigDecimal maxLoanPeriod) {
        this.maxLoanPeriod = maxLoanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.MIN_LOAN_PERIOD
     *
     * @return the value of PRODUCT_BASIC_INFO.MIN_LOAN_PERIOD
     *
     * @mbggenerated
     */
    public BigDecimal getMinLoanPeriod() {
        return minLoanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.MIN_LOAN_PERIOD
     *
     * @param minLoanPeriod the value for PRODUCT_BASIC_INFO.MIN_LOAN_PERIOD
     *
     * @mbggenerated
     */
    public void setMinLoanPeriod(BigDecimal minLoanPeriod) {
        this.minLoanPeriod = minLoanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PERIOD_UNIT
     *
     * @return the value of PRODUCT_BASIC_INFO.PERIOD_UNIT
     *
     * @mbggenerated
     */
    public String getPeriodUnit() {
        return periodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PERIOD_UNIT
     *
     * @param periodUnit the value for PRODUCT_BASIC_INFO.PERIOD_UNIT
     *
     * @mbggenerated
     */
    public void setPeriodUnit(String periodUnit) {
        this.periodUnit = periodUnit == null ? null : periodUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.YIELD
     *
     * @return the value of PRODUCT_BASIC_INFO.YIELD
     *
     * @mbggenerated
     */
    public BigDecimal getYield() {
        return yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.YIELD
     *
     * @param yield the value for PRODUCT_BASIC_INFO.YIELD
     *
     * @mbggenerated
     */
    public void setYield(BigDecimal yield) {
        this.yield = yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.FEE_RATE
     *
     * @return the value of PRODUCT_BASIC_INFO.FEE_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.FEE_RATE
     *
     * @param feeRate the value for PRODUCT_BASIC_INFO.FEE_RATE
     *
     * @mbggenerated
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.MONTH_RATE
     *
     * @return the value of PRODUCT_BASIC_INFO.MONTH_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getMonthRate() {
        return monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.MONTH_RATE
     *
     * @param monthRate the value for PRODUCT_BASIC_INFO.MONTH_RATE
     *
     * @mbggenerated
     */
    public void setMonthRate(BigDecimal monthRate) {
        this.monthRate = monthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.DAY_RATE
     *
     * @return the value of PRODUCT_BASIC_INFO.DAY_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getDayRate() {
        return dayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.DAY_RATE
     *
     * @param dayRate the value for PRODUCT_BASIC_INFO.DAY_RATE
     *
     * @mbggenerated
     */
    public void setDayRate(BigDecimal dayRate) {
        this.dayRate = dayRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PUT_MONEY_TIME
     *
     * @return the value of PRODUCT_BASIC_INFO.PUT_MONEY_TIME
     *
     * @mbggenerated
     */
    public BigDecimal getPutMoneyTime() {
        return putMoneyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PUT_MONEY_TIME
     *
     * @param putMoneyTime the value for PRODUCT_BASIC_INFO.PUT_MONEY_TIME
     *
     * @mbggenerated
     */
    public void setPutMoneyTime(BigDecimal putMoneyTime) {
        this.putMoneyTime = putMoneyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PUT_MONEY_TIME_UNIT
     *
     * @return the value of PRODUCT_BASIC_INFO.PUT_MONEY_TIME_UNIT
     *
     * @mbggenerated
     */
    public String getPutMoneyTimeUnit() {
        return putMoneyTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PUT_MONEY_TIME_UNIT
     *
     * @param putMoneyTimeUnit the value for PRODUCT_BASIC_INFO.PUT_MONEY_TIME_UNIT
     *
     * @mbggenerated
     */
    public void setPutMoneyTimeUnit(String putMoneyTimeUnit) {
        this.putMoneyTimeUnit = putMoneyTimeUnit == null ? null : putMoneyTimeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.REPAY_MANNER
     *
     * @return the value of PRODUCT_BASIC_INFO.REPAY_MANNER
     *
     * @mbggenerated
     */
    public String getRepayManner() {
        return repayManner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.REPAY_MANNER
     *
     * @param repayManner the value for PRODUCT_BASIC_INFO.REPAY_MANNER
     *
     * @mbggenerated
     */
    public void setRepayManner(String repayManner) {
        this.repayManner = repayManner == null ? null : repayManner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PROD_NAME_EN
     *
     * @return the value of PRODUCT_BASIC_INFO.PROD_NAME_EN
     *
     * @mbggenerated
     */
    public String getProdNameEn() {
        return prodNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PROD_NAME_EN
     *
     * @param prodNameEn the value for PRODUCT_BASIC_INFO.PROD_NAME_EN
     *
     * @mbggenerated
     */
    public void setProdNameEn(String prodNameEn) {
        this.prodNameEn = prodNameEn == null ? null : prodNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.WEIGHT
     *
     * @return the value of PRODUCT_BASIC_INFO.WEIGHT
     *
     * @mbggenerated
     */
    public Short getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.WEIGHT
     *
     * @param weight the value for PRODUCT_BASIC_INFO.WEIGHT
     *
     * @mbggenerated
     */
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.PROD_CATG
     *
     * @return the value of PRODUCT_BASIC_INFO.PROD_CATG
     *
     * @mbggenerated
     */
    public String getProdCatg() {
        return prodCatg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.PROD_CATG
     *
     * @param prodCatg the value for PRODUCT_BASIC_INFO.PROD_CATG
     *
     * @mbggenerated
     */
    public void setProdCatg(String prodCatg) {
        this.prodCatg = prodCatg == null ? null : prodCatg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.APPLY_ACTION_TYPE
     *
     * @return the value of PRODUCT_BASIC_INFO.APPLY_ACTION_TYPE
     *
     * @mbggenerated
     */
    public Short getApplyActionType() {
        return applyActionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.APPLY_ACTION_TYPE
     *
     * @param applyActionType the value for PRODUCT_BASIC_INFO.APPLY_ACTION_TYPE
     *
     * @mbggenerated
     */
    public void setApplyActionType(Short applyActionType) {
        this.applyActionType = applyActionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_BASIC_INFO.APPPY_METHOD
     *
     * @return the value of PRODUCT_BASIC_INFO.APPPY_METHOD
     *
     * @mbggenerated
     */
    public String getApppyMethod() {
        return apppyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_BASIC_INFO.APPPY_METHOD
     *
     * @param apppyMethod the value for PRODUCT_BASIC_INFO.APPPY_METHOD
     *
     * @mbggenerated
     */
    public void setApppyMethod(String apppyMethod) {
        this.apppyMethod = apppyMethod == null ? null : apppyMethod.trim();
    }
}