package com.yumi.cash.app.server.dal;

import com.yumi.cash.app.server.dao.ProductBasicInfoDO;
import com.yumi.cash.app.server.dao.ProductBasicInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductBasicInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int countByExample(ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int insert(ProductBasicInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int insertSelective(ProductBasicInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    List<ProductBasicInfoDO> selectByExampleWithBLOBs(ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    List<ProductBasicInfoDO> selectByExample(ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    ProductBasicInfoDO selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductBasicInfoDO record, @Param("example") ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProductBasicInfoDO record, @Param("example") ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductBasicInfoDO record, @Param("example") ProductBasicInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductBasicInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProductBasicInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_BASIC_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductBasicInfoDO record);
}